channels:
  - pytorch
  - conda-canary
  - defaults
dependencies:
  - python=3.10.8
  - pip:
    - gensim==4.3.0
    - ipdb==0.13.11
    - matplotlib==3.6.2
    - nltk==3.8.1
    - numpy==1.23.5
    - pandas==1.5.3
    - pip==22.3.1
    - scikit-learn==1.2.0
    - scipy==1.9.3
    - seaborn==0.12.2
    - spacy==3.5.0
    - torch==1.13.1
    - transformers==4.25.1